### ISSUE TITLE
Read and Analyze a flow chart

### ISSUE THREAD

**Issue by ashwarhussain** [KrishKasula/txtoflow#4]
Its not a issue actually .. but I am looking at an option where in a flow chart image is uploaded and we need to read it and re-draw it.

So if image can be read and data can be extracted that Node A is getting connected to Node B etc then we can use your library to get the flowchart going. Do you have anything on this please.

**Comment by KrishKasula** [comment]
Sorry @ashwarhussain 
Not an expert in the image processing domain.

Closing this hence

Keep in touch

-
Krishna
